### ISSUE TITLE
Use `pittgoogle-client` instead of `pgb-broker-utils`

### ISSUE THREAD

**Issue by troyraen** [mwvgroup/pittgoogle-user#5]
Update all necessary code/files to remove the `pgb-broker-utils` python package, and instead use tools from `pittgoogle-client`.

mwvgroup/pittgoogle-client#6 is a PR containing a major refactor of `pittgoogle-client`, so this likely needs to wait until that is done. After that happens, we'll need to check and see which functions/classes still need to be added to `pittgoogle-client` for this to work (and then add them).

**Comment by wmwv** [comment]
https://github.com/mwvgroup/pittgoogle-client/pull/6 has been merged.  What's the next step for this current Issue?

**Comment by troyraen** [comment]
Thanks, we need to evaluate what still needs to be added to `pittgoogle-client`. Below is my rundown from looking at the imports in classifier/main.py. Perhaps I can spend a little time this weekend to knock out the simpler ones. @wmwv if there are particular items that would be helpful to prioritize for #13, let me know.

```
from broker_utils import data_utils, gcp_utils, math
```

This is using: 

- [ ] [broker_utils.data_utils.alert_dict_to_dataframe](https://github.com/mwvgroup/Pitt-Google-Broker/blob/50e392e19eeeea7abbc3acce943e667b50b48e3e/broker/broker_utils/broker_utils/data_utils.py#L288), which should be easy to port over
- [ ] [broker_utils.gcp_utils.insert_rows_bigquery](https://github.com/mwvgroup/Pitt-Google-Broker/blob/50e392e19eeeea7abbc3acce943e667b50b48e3e/broker/broker_utils/broker_utils/gcp_utils.py#L247), which is easy to port over -- but, 1) the call to `get_table` causes problems at high alert rates (see https://github.com/mwvgroup/Pitt-Google-Broker/issues/96#issuecomment-983282727) and should be dropped; and 2) we should just ditch this call altogether and use a [BigQuery subscription](https://cloud.google.com/pubsub/docs/bigquery) instead.
- [ ] [broker_utils.gcp_utils.publish_pubsub](https://github.com/mwvgroup/Pitt-Google-Broker/blob/50e392e19eeeea7abbc3acce943e667b50b48e3e/broker/broker_utils/broker_utils/gcp_utils.py#L32). I know where/how I want to add this to pittgoogle-client and should just do it.
- [ ] broker_utils.math is being import but not used, so I didn't look at it further.

```
from broker_utils.types import AlertIds
```

- [ ] `AlertIds` is awkward and clunky to use and I want to drop it. The new pittgoogle-client has an `Alert` class and I can look at making the IDs easily accessible from there. In the meantime, the IDs can just be pulled directly from the alert.

```
from broker_utils.schema_maps import load_schema_map, get_value
```

- [ ] For now, we should probably just port [broker_utils.schema_maps](https://github.com/mwvgroup/Pitt-Google-Broker/blob/develop/broker/broker_utils/broker_utils/schema_maps.py) over. Longer term, I'll need to spend a little more time thinking this through. The way that schema maps are currently implemented is a pain and I don't have a clear solution right now. 

```
from broker_utils.data_utils import open_alert
```

- [ ] [broker_utils.data_utils.open_alert](https://github.com/mwvgroup/Pitt-Google-Broker/blob/50e392e19eeeea7abbc3acce943e667b50b48e3e/broker/broker_utils/broker_utils/data_utils.py#L75) is a very convenient function that accepts alerts in many different forms and hides a big ol' mess underneath. I think I can do a much cleaner implementation using class methods on [pittgoogle.pubsub.Alert](https://github.com/mwvgroup/pittgoogle-client/blob/1619f575bac343fa713ea0a2d92b1c78a07d941f/pittgoogle/pubsub.py#L439) (e.g., `Alert.from_cloud_run`, `Alert.from_cloud_functions`, `Alert.from_path`, etc.).

**Comment by troyraen** [comment]
> The way that schema maps are currently implemented is a pain and I don't have a clear solution right now.

Jotting down some thoughts:
This should probably be handled by `pittgoogle.pubsub.Alert` without the user having to do anything except specify which survey the alert is coming from (and possibly the schema version). The schema maps should be packaged with the pittgoogle-client so that they don't have to be supplied or retrieved from somewhere else.

**Comment by troyraen** [comment]
I've started working on this, but realized that simply porting these functions over is really not the way to go. Most of this should be handled by the `pittgoogle.pubsub.Alert` class, so I'm implementing new methods there.
